
server:
  port: 8501

eureka:
  client:
    serviceUrl:
          defaultZone: http://peer1:8100/eureka/

spring:
  application:
    name: gongwenserver
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databasename=BankOfChina
    username: sa
    password: 123qwe
