eureka:
    client:
      serviceUrl:
          defaultZone: http://localhost:8761/eureka/
server:
    port: 8769

spring:
  application:
        name: zuulserver

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

zuul:
    routes:
        api-a:
            path: /webservice/**
            serviceId: webservice

    host:
      connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
      socket-timeout-millis: 60000   #socket超时


