eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8761/eureka/
server:
  port: 8005
spring:
  application:
    name: webservice
fegin:
  client:
      config:
          connectTimeout: 2000
          readTimeout: 50000
#  hystric:
#          enabled: true